 CLASS zdj_tcl_tutposheader  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS zdj_tcl_tutposheader  IMPLEMENTATION.
 ENDCLASS.
